
FROM adoptopenjdk/openjdk11
EXPOSE 8070

RUN apt-get update -y
#RUN apt-get install -y libxrender1 libxtst6 libxi6

RUN mkdir ./MainRasp/

WORKDIR ./MainRasp/
COPY ./sprint3_project/build/libs/it.unibo.ctxrasp.MainCtxraspKt-1.0.jar ./
COPY ./distribution/local/*.pl ./
COPY ./distribution/local/*.json ./

CMD [ "java", "-jar", "it.unibo.ctxrasp.MainCtxraspKt-1.0.jar" ]