
FROM adoptopenjdk/openjdk11
EXPOSE 8050

RUN apt-get update -y

RUN mkdir ./MainWasteservice/

WORKDIR ./MainWasteservice/
COPY ./sprint3_project/build/libs/it.unibo.ctxwasteservice.MainCtxwasteserviceKt-1.0.jar ./
COPY ./distribution/local/*.pl ./
COPY ./distribution/local/*.json ./

CMD [ "java", "-jar", "it.unibo.ctxwasteservice.MainCtxwasteserviceKt-1.0.jar" ]