/* Generated by AN DISI Unibo */ 
package it.unibo.wasteservice

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Wasteservice ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		
				var CurrentMaterial: ws.Material
				var CurrentQuantity: Float
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						discardMessages = true
						println("	WASTESERVICE | started.")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="handleStoreRequest",cond=whenRequest("storeRequest"))
				}	 
				state("idle") { //this:State
					action { //it:State
						println("	WASTESERVICE | idle - waiting for storeRequests")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="handleStoreRequest",cond=whenRequest("storeRequest"))
				}	 
				state("handleStoreRequest") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("storeRequest(MATERIAL,QUANTITY)"), Term.createTerm("storeRequest(MATERIAL,QUANTITY)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												CurrentMaterial = ws.Material.valueOf(payloadArg(0))
												CurrentQuantity = payloadArg(1).toFloat()
								println("	WASTESERVICE | received store request: $CurrentQuantity KG of $CurrentMaterial")
								if(  ws.WasteServiceStatusManager.checkIfDepositPossible(CurrentMaterial, CurrentQuantity)  
								 ){
													ws.WasteServiceStatusManager.updateBox(CurrentMaterial, CurrentQuantity)
								request("depositRequest", "depositRequest($CurrentMaterial,$CurrentQuantity)" ,"transporttrolley" )  
								println("	WASTESERVICE | sended depositRequest to trolley")
								}
								else
								 {answer("storeRequest", "loadRejected", "loadRejected(_)","smartdevicemock"   )  
								 println("	WASTESERVICE | rejected request from smartdevice")
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t14",targetState="handlePickupReply",cond=whenReply("pickupDone"))
				}	 
				state("handlePickupReply") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("pickupDone(RESULT)"), Term.createTerm("pickupDone(RESULT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var Res = payloadArg(0).toString()  
								if(  Res == "OK"  
								 ){println("	WASTESERVICE | arrived pickupDone reply OK")
								answer("storeRequest", "loadAccepted", "loadAccepted(_)","smartdevicemock"   )  
								}
								else
								 {println("	WASTESERVICE | arrived pickupDone reply NO - FATAL ERROR")
								 answer("storeRequest", "loadRejected", "loadRejected(_)","smartdevicemock"   )  
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
}
