/* Generated by AN DISI Unibo */ 
package it.unibo.ctxrequest
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "wasteservice.pl", "sysRules.pl","ctxrequest"
	)
}

