/* Generated by AN DISI Unibo */ 
package it.unibo.ctxrasp
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "192.168.1.124", this, "sprint2_project.pl", "sysRules.pl","ctxrasp"
	)
}

