/* Generated by AN DISI Unibo */ 
package it.unibo.ctxtrolley
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "192.168.1.125", this, "sprint2_project.pl", "sysRules.pl","ctxtrolley"
	)
}

