/* Generated by AN DISI Unibo */ 
package it.unibo.ctxwasteservicegui
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "wasteservice_gui.pl", "sysRules.pl","ctxwasteservicegui"
	)
}

