/* Generated by AN DISI Unibo */ 
package it.unibo.transporttrolley

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Transporttrolley ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		 
				lateinit var Mat: ws.Material
				var Qty: Float
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						println("	TRANSPORTTROLLEY | started...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						println("	TRANSPORTROLLEY | waiting for requests...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="handleDepositRequest",cond=whenRequest("depositRequest"))
				}	 
				state("handleDepositRequest") { //this:State
					action { //it:State
						updateResourceRep( "transporttrolley(handleDepositRequest)"  
						)
						println("	TRANSPORTTROLLEY | moving to indoor")
						updateResourceRep( "transporttrolley(moving_Indoor)"  
						)
						delay(1000) 
						println("	TRANSPORTTROLLEY | arrived to indoor")
						updateResourceRep( "transporttrolley(arrived_Indoor)"  
						)
						if( checkMsgContent( Term.createTerm("depositRequest(MATERIAL,QUANTITY)"), Term.createTerm("depositRequest(MATERIAL,QUANTITY)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Mat = ws.Material.valueOf(payloadArg(0))  
								 Qty = payloadArg(1).toFloat()  
								answer("depositRequest", "pickupDone", "pickupDone(ok)","wasteservice"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="moveToGlassBox", cond=doswitchGuarded({ Mat == ws.Material.GLASS  
					}) )
					transition( edgeName="goto",targetState="moveToPlasticBox", cond=doswitchGuarded({! ( Mat == ws.Material.GLASS  
					) }) )
				}	 
				state("moveToPlasticBox") { //this:State
					action { //it:State
						println("	TRANSPORT TROLLEY | moving to PlasticBox")
						updateResourceRep( "transporttrolley(moving_PlasticBox)"  
						)
						delay(1000) 
						println("	TRANSPORT TROLLEY | arrived to PlasticBox")
						updateResourceRep( "transporttrolley(arrived_PlasticBox)"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="doDeposit", cond=doswitch() )
				}	 
				state("moveToGlassBox") { //this:State
					action { //it:State
						println("	TRANSPORT TROLLEY | moving to GlassBox")
						updateResourceRep( "transporttrolley(moving_GlassBox)"  
						)
						delay(1000) 
						println("	TRANSPORT TROLLEY | arrived to GlassBox")
						updateResourceRep( "transporttrolley(arrived_GlassBox)"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="doDeposit", cond=doswitch() )
				}	 
				state("doDeposit") { //this:State
					action { //it:State
						println("	TRANSPORT TROLLEY | doing the deposit")
						delay(500) 
						println("	TRANSPORT TROLLEY | deposit done")
						updateResourceRep( "transporttrolley(depositDone)"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="endRequest", cond=doswitch() )
				}	 
				state("endRequest") { //this:State
					action { //it:State
						println("	TRANSPORTTROLLEY | moving back to home")
						updateResourceRep( "transporttrolley(moving_Home)"  
						)
						delay(1000) 
						println("	TRANSPORTTROLLEY | arrived to home")
						updateResourceRep( "transporttrolley(arrived_Home)"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t14",targetState="handleDepositRequest",cond=whenRequest("depositRequest"))
				}	 
			}
		}
}
