/* Generated by AN DISI Unibo */ 
package it.unibo.ctxwasteservice_prob
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "wasteservice_system.pl", "sysRules.pl","ctxwasteservice_prob"
	)
}

