/* Generated by AN DISI Unibo */ 
package it.unibo.ctxwasteservice_test
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "sprint3_problem_single_context.pl", "sysRules.pl","ctxwasteservice_test"
	)
}

