
FROM adoptopenjdk/openjdk11
EXPOSE 8060

RUN apt-get update -y

RUN mkdir ./MainWasteservice/

WORKDIR ./MainTrolley/
COPY ./build/libs/it.unibo.ctxtrolley.MainCtxtrolleyKt-1.0.jar ./
COPY ./docker/local/*.pl ./
COPY ./docker/local/*.json ./
COPY ./docker/distributed/*.bin ./

CMD [ "java", "-jar", "it.unibo.ctxtrolley.MainCtxtrolleyKt-1.0.jar" ]