/* Generated by AN DISI Unibo */ 
package it.unibo.ctxpath
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "provapath.pl", "sysRules.pl","ctxpath"
	)
}

