/* Generated by AN DISI Unibo */ 
package it.unibo.transporttrolley

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Transporttrolley ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		
				var CarriedMaterialType = ""
				var CarriedQuantity = 0.0
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("	TransportTrolley | init at HOME")
					}
					 transition(edgeName="t01",targetState="go_indoor",cond=whenDispatch("requestDeposit"))
				}	 
				state("go_home") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("	TransportTrolley | going back to HOME")
						delay(500) 
					}
					 transition( edgeName="goto",targetState="home", cond=doswitch() )
				}	 
				state("home") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("	TransportTrolley | at HOME")
					}
					 transition( edgeName="goto",targetState="done", cond=doswitch() )
				}	 
				state("go_indoor") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("	TransportTrollye | going to INDOOR port")
						if( checkMsgContent( Term.createTerm("requestDeposit(MATERIAL,QUANTITY)"), Term.createTerm("requestDeposit(MATERIAL,QUANTITY)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												CarriedMaterialType = payloadArg(0)
												CarriedQuantity = payloadArg(1).toDouble() 
						}
						delay(500) 
					}
					 transition( edgeName="goto",targetState="indoor", cond=doswitch() )
				}	 
				state("indoor") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("	TransportTrolley | At INDOOR port, picking up $CarriedQuantity KG of $CarriedMaterialType")
					}
					 transition( edgeName="goto",targetState="go_box", cond=doswitch() )
				}	 
				state("go_box") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("	TransportTrolley | going to $CarriedMaterialType box")
						if(  CarriedMaterialType == "plastic"  
						 ){delay(500) 
						}
						else
						 {delay(700) 
						 }
					}
					 transition( edgeName="goto",targetState="box", cond=doswitch() )
				}	 
				state("box") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("	TransportTrolley | At $CarriedMaterialType box, unloading $CarriedQuantity KG of $CarriedMaterialType")
						delay(250) 
						forward("updateWasteService", "updateWasteService($CarriedMaterialType,$CarriedQuantity)" ,"wasteservice" ) 
						
									CarriedMaterialType = ""
									CarriedQuantity = 0.0
					}
					 transition( edgeName="goto",targetState="go_home", cond=doswitch() )
				}	 
				state("done") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("	TransportTrolley | done")
					}
					 transition( edgeName="goto",targetState="init", cond=doswitch() )
				}	 
			}
		}
}
