version: "3.3"
services:
  statusmanager:
    image: statusmanager
    build:
      context: ../../../
      dockerfile: distribution/distributed/web/Dockerfile-statusmanager
    container_name: statusmanager
    expose:
      - "8085"
    ports:
      - "8085:8085"