version: "3.3"
services:
  wenv:
    image: wenvl
    build:
      context: ../../../../it.unibo.virtualRobot2020/
    container_name: wenvl
    expose:
      - "8090"
    ports:
      - "8090:8090"
      - "8091:8091"