version: "3.3"
services:
  wasteservice:
    image: wasteservice
    build: 
      context: ../../
      dockerfile: distribution/distributed/Dockerfile-ctxwasteservice 
    container_name: wasteservice
    expose:
      - "8050"
    depends_on:
      - "wenv"
    ports:
      - "0.0.0.0:8050:8050"
  trolley:
    image: trolley
    build:
      context: ../../
      dockerfile: distribution/distributed/Dockerfile-ctxtrolley
    container_name: trolley
    expose:
      - "8060"
    depends_on:
      - "wasteservice"
    ports:
      - "8060:8060"
  statusmanager:
    image: statusmanager
    build:
      context: ../../
      dockerfile: distribution/distributed/Dockerfile-statusmanager
    container_name: statusmanager
    expose:
      - "8085"
    depends_on:
      - "wasteservice"
      - "trolley"
    ports:
      - "8085:8085"
  #wenv:
  #  image: docker.io/natbodocker/virtualrobotdisi:4.0
  #  ports:
  #    - 8090:8090
  #    - 8091:8091
  wenv:
    image: wenvl
    build:
      context: ../../../it.unibo.virtualRobot2020/
    container_name: wenvl
    ports:
      - "8090:8090"
      - "8091:8091"