
FROM adoptopenjdk/openjdk11
EXPOSE 8060

RUN apt-get update -y

RUN mkdir ./MainWasteservice/

WORKDIR ./MainTrolley/
COPY ./build/libs/it.unibo.ctxtrolley.MainCtxtrolleyKt-1.0.jar ./
COPY ./docker/distributed/*.pl ./
COPY ./docker/distributed/*.json ./

CMD [ "java", "-jar", "it.unibo.ctxtrolley.MainCtxtrolleyKt-1.0.jar" ]