version: "3.3"
services:
  rasp:
    privileged: true
    devices:
      - "/dev/mem"
    volumes:
      - "/proc:/proc"
      - "/sys/firmware/devicetree:/sys/firmware/devicetree"
    image: ${IP}:5000/rasp
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile-ctxrasp
    container_name: rasp
    #environment:
    #  - DISPLAY=IP:0
    expose:
      - "8070"
    networks:
      - wsnetwork
    ports:
      - "8070:8070"
networks:
  wsnetwork: