version: "3.3"
services:
  rasp:
    platform: "linux/arm/v7"
    privileged: true
    #devices:
    #  - "/dev/mem"
    #volumes:
    #  - "/proc:/proc"
    #  - "/sys/firmware/devicetree:/sys/firmware/devicetree"
    image: rasp
    build:
      context: ../../
      dockerfile: docker/distributed/Dockerfile-ctxrasp
    container_name: rasp
    ports:
      - "8070:8070"