
FROM adoptopenjdk/openjdk11
EXPOSE 8070

COPY ./resources/wsSonar/wiringpi-2.61-1-armhf.deb ./

RUN apt-get update -y
RUN apt-get install -y sudo
RUN apt-get install -y build-essential 
RUN apt-get install -y g++
RUN apt install ./wiringpi-2.61-1-armhf.deb

RUN mkdir ./MainRasp/

WORKDIR ./MainRasp/
COPY ./build/libs/it.unibo.ctxrasp.MainCtxraspKt-1.0.jar ./
COPY ./docker/distributed/*.pl ./
COPY ./docker/distributed/*.json ./
COPY ./resources/wsLed/led25GpioTurnOff.sh ./
COPY ./resources/wsLed/led25GpioTurnOn.sh ./
COPY ./resources/wsSonar/SonarAlone.c ./

RUN g++ SonarAlone.c -l wiringPi -o SonarAlone

CMD [ "java", "-jar", "it.unibo.ctxrasp.MainCtxraspKt-1.0.jar" ]