version: "3.3"
services:
  wasteservice:
    image: wasteservice
    build: 
      context: ../../
      dockerfile: docker/distributed/Dockerfile-ctxwasteservice 
    container_name: wasteservice
    depends_on:
      - "wenv"
    network_mode: "host"
  trolley:
    image: trolley
    build:
      context: ../../
      dockerfile: docker/distributed/Dockerfile-ctxtrolley
    container_name: trolley
    depends_on:
      - "wasteservice"
    network_mode: "host"
  wenv:
    image: wenvl
    build:
      context: ../../../../it.unibo.virtualRobot2020/
    container_name: wenvl
    ports:
      - "8090:8090"
      - "8091:8091"
