/* Generated by AN DISI Unibo */ 
package it.unibo.ctxpercorso
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "systempercorso.pl", "sysRules.pl","ctxpercorso"
	)
}

