/* Generated by AN DISI Unibo */ 
package it.unibo.gui

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Gui ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				var POSITION = "HOME"
				var TROLLEY = "IDLE"
				var LED = "OFF"
				var PLASTIC = 0.0
				var GLASS = 0.0
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
					}
					 transition(edgeName="t00",targetState="handle_position",cond=whenEvent("update_position"))
					transition(edgeName="t01",targetState="handle_trolley_status",cond=whenEvent("update_trolley_status"))
					transition(edgeName="t02",targetState="handle_led_status",cond=whenEvent("update_led_status"))
					transition(edgeName="t03",targetState="handle_weight",cond=whenEvent("update_weight"))
				}	 
				state("handle_position") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("update_position(POSITION)"), Term.createTerm("update_position(POSITION)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												POSITION = payloadArg(0)	
						}
					}
					 transition( edgeName="goto",targetState="init", cond=doswitch() )
				}	 
				state("handle_trolley_status") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("update_trolley_status(STATUS)"), Term.createTerm("update_trolley_status(STATUS)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												TROLLEY = payloadArg(0)	
						}
					}
					 transition( edgeName="goto",targetState="init", cond=doswitch() )
				}	 
				state("handle_led_status") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("update_led_status(STATUS)"), Term.createTerm("update_led_status(STATUS)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												LED = payloadArg(0)	
						}
					}
					 transition( edgeName="goto",targetState="init", cond=doswitch() )
				}	 
				state("handle_weight") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("update_weight(GLASS,PLASTIC)"), Term.createTerm("update_WEIGHT(GLASS,PLASTIC)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												var GLASS = payloadArg(0)
												var PLASTIC = payloadArg(1)
						}
					}
					 transition( edgeName="goto",targetState="init", cond=doswitch() )
				}	 
			}
		}
}
